Controllers/ToursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgenciaViajes.Models;

namespace AgenciaViajes.Controllers
{
    public class ToursController : Controller
    {
        private readonly AgenciaVContext _context;

        public ToursController(AgenciaVContext context)
        {
            _context = context;
        }

        // GET: Tours
        public async Task<IActionResult> Index()
        {
            var agenciaVContext = _context.Tours.Include(t => t.EstadoNavigation);
            return View(await agenciaVContext.ToListAsync());
        }

        // GET: Tours/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tours == null)
            {
                return NotFound();
            }

            var tour = await _context.Tours
                .Include(t => t.EstadoNavigation)
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (tour == null)
            {
                return NotFound();
            }

            return View(tour);
        }

        // GET: Tours/Create
        public IActionResult Create()
        {
            var paisesfiltro = _context.Aeropuerts.Where(m => m.Estado == "HABILITADO").Select(a => a.Pais).Distinct().ToList();

            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1");
            ViewData["PaisOrigen"] = new SelectList(paisesfiltro);
            return View();
        }

        // POST: Tours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProducto,Precio,Descripción,NombreTour,Destinos,Pais,FechaInicio,FechaFin,DatosImagen,Capacidad,Estado")] Tour tour, IFormFile imagen)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrWhiteSpace(tour.Estado))
                {
                    tour.Estado = "HABILITADO";
                }

                if (imagen != null && imagen.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await imagen.CopyToAsync(memoryStream);
                        tour.DatosImagen = memoryStream.ToArray();
                    }
                }

                _context.Add(tour);
                await _context.SaveChangesAsync();
                // Después de guardar exitosamente, redirigir al usuario a la acción "Index" del controlador actual
                return RedirectToAction(nameof(Index));
            }
            var paisesfiltro = _context.Aeropuerts.Where(m => m.Estado == "HABILITADO").Select(a => a.Pais).Distinct().ToList();

            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1", tour.Estado);
            ViewData["PaisOrigen"] = new SelectList(paisesfiltro);
            return View(tour);
        }

        // GET: Tours/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tours == null)
            {
                return NotFound();
            }

            var tour = await _context.Tours.FindAsync(id);
            if (tour == null)
            {
                return NotFound();
            }
            var paisesfiltro = _context.Aeropuerts.Where(m => m.Estado == "HABILITADO").Select(a => a.Pais).Distinct().ToList();

            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1", tour.Estado);
            ViewData["PaisOrigen"] = new SelectList(paisesfiltro);
            return View(tour);
        }

        // POST: Tours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProducto,Precio,Descripción,NombreTour,Destinos,Pais,FechaInicio,FechaFin,DatosImagen,Capacidad,Estado")] Tour tour, IFormFile imagen)
        {
            if (id != tour.IdProducto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                try
                {
                    if (imagen != null && imagen.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            await imagen.CopyToAsync(memoryStream);
                            tour.DatosImagen = memoryStream.ToArray();
                        }
                    }

                    _context.Update(tour);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TourExists(tour.IdProducto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var paisesfiltro = _context.Aeropuerts.Where(m => m.Estado == "HABILITADO").Select(a => a.Pais).Distinct().ToList();

            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1", tour.Estado);
            ViewData["PaisOrigen"] = new SelectList(paisesfiltro);
            return View(tour);
        }

        // GET: Tours/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tours == null)
            {
                return NotFound();
            }

            var tour = await _context.Tours
                .Include(t => t.EstadoNavigation)
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (tour == null)
            {
                return NotFound();
            }

            return View(tour);
        }

        // POST: Tours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tours == null)
            {
                return Problem("Entity set 'AgenciaVContext.Tours'  is null.");
            }
            var tour = await _context.Tours.FindAsync(id);
            if (tour != null)
            {
                tour.Estado = "DESHABILITADO"; // Cambiar el estado en lugar de eliminar
                _context.Update(tour); // Actualizar el estado en la base de datos
                await _context.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool TourExists(int id)
        {
          return (_context.Tours?.Any(e => e.IdProducto == id)).GetValueOrDefault();
        }
    }
}

Controllers/VueloesController.cs
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgenciaViajes.Models;

namespace AgenciaViajes.Controllers
{
    public class VueloesController : Controller
    {
        private readonly AgenciaVContext _context;

        public VueloesController(AgenciaVContext context)
        {
            _context = context;
        }

        // GET: Vueloes
        public async Task<IActionResult> Index()
        {
            var agenciaVContext = _context.Vuelos.Include(v => v.EstadoNavigation).Include(v => v.IdAerolineaNavigation).Include(v => v.IdAeropuertoDestinoNavigation).Include(v => v.IdAeropuertoOrigenNavigation);
            return View(await agenciaVContext.ToListAsync());
        }

        // GET: Vueloes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vuelos == null)
            {
                return NotFound();
            }

            var vuelo = await _context.Vuelos
                .Include(v => v.EstadoNavigation)
                .Include(v => v.IdAerolineaNavigation)
                .Include(v => v.IdAeropuertoDestinoNavigation)
                .Include(v => v.IdAeropuertoOrigenNavigation)
                .FirstOrDefaultAsync(m => m.IdVuelo == id);
            if (vuelo == null)
            {
                return NotFound();
            }

            return View(vuelo);
        }

        // GET: Vueloes/Create
        public IActionResult Create()
        {
            // Filtrar los elementos cuyo estado es "HABILITADO"
            var modeloAerolineas = _context.Aerolineas.Where(m => m.Estado == "HABILITADO").ToList();
            var modeloAeropuerts = _context.Aeropuerts.Where(m => m.Estado == "HABILITADO").ToList();
            var paisesfiltro = _context.Aeropuerts.Where(m => m.Estado == "HABILITADO").Select(a => a.Pais).Distinct().ToList();


            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1");
            ViewData["IdAerolinea"] = new SelectList(modeloAerolineas, "IdAerolinea", "Aerolinea1");
            ViewData["PaisOrigen"] = new SelectList(paisesfiltro);
            ViewData["ProvinciaOrigen"] = new SelectList(_context.Aeropuerts, "Provincia", "Provincia");
            ViewData["PaisDestino"] = new SelectList(paisesfiltro);
            ViewData["ProvinciaDestino"] = new SelectList(_context.Aeropuerts, "Provincia", "Provincia");
            ViewData["IdAeropuertoDestino"] = new SelectList(modeloAeropuerts, "IdAeropuerto", "Aeropuerto");
            ViewData["IdAeropuertoOrigen"] = new SelectList(modeloAeropuerts, "IdAeropuerto", "Aeropuerto");
            return View();
        }

        // POST: Vueloes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVuelo,IdAerolinea,FechaInicio,FechaFinal,IdAeropuertoOrigen,IdAeropuertoDestino,PrecioV,Estado")] Vuelo vuelo)
        {

            if (ModelState.IsValid)
            {

                if (string.IsNullOrWhiteSpace(vuelo.Estado))
                {
                    vuelo.Estado = "HABILITADO"; // Establece el valor por defecto si no se especifica
                }


                _context.Add(vuelo);
                await _context.SaveChangesAsync();

                CrearAsientoA(vuelo);
                CrearAsientoB(vuelo);
                CrearAsientoC(vuelo);
                CrearAsientoD(vuelo);
                CrearAsientoE(vuelo);
                CrearAsientoF(vuelo);

                return RedirectToAction(nameof(Index));
            }
            var paisesfiltro = _context.Aeropuerts.Where(m => m.Estado == "HABILITADO").Select(a => a.Pais).Distinct().ToList();

            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1");
            ViewData["IdAerolinea"] = new SelectList(_context.Aerolineas, "IdAerolinea", "Aerolinea1");
            ViewData["PaisOrigen"] = new SelectList(paisesfiltro);
            ViewData["ProvinciaOrigen"] = new SelectList(_context.Aeropuerts, "Provincia", "Provincia");
            ViewData["PaisDestino"] = new SelectList(paisesfiltro);
            ViewData["ProvinciaDestino"] = new SelectList(_context.Aeropuerts, "Provincia", "Provincia");
            ViewData["IdAeropuertoDestino"] = new SelectList(_context.Aeropuerts, "IdAeropuerto", "Aeropuerto", vuelo.IdAeropuertoDestino);
            ViewData["IdAeropuertoOrigen"] = new SelectList(_context.Aeropuerts, "IdAeropuerto", "Aeropuerto", vuelo.IdAeropuertoOrigen);
            return View(vuelo);
        }


        //ASIENTOS CREACIÓN
        private void CrearAsientoA(Vuelo vuelo)
        {
            // Obtener el ID del vuelo recién creado
            var nuevoVueloId = vuelo.IdVuelo;

            for (int numeroAsiento = 1; numeroAsiento <= 29; numeroAsiento++)
            {

                if (numeroAsiento == 4)
                {
                    // Saltar el número 4
                    continue;
                };
                if (numeroAsiento >= 11 && numeroAsiento <= 17)
                {
                    // Saltar el rango del 11 al 17
                    continue;
                }


                var numeroAsientoFormateadoA = "A" + numeroAsiento.ToString("D2");

                var asientoPrimeraClaseA = new Asiento
                {
                    NumAsiento = numeroAsientoFormateadoA,
                    Clase = ObtenerClaseDelAsiento(numeroAsiento),
                    Disponibilidad = "DISPONIBLE",
                    PrecioV = ObtenerPrecioDeLaClase(ObtenerClaseDelAsiento(numeroAsiento)),
                    IdVuelo = nuevoVueloId
                };


                _context.Asientos.Add(asientoPrimeraClaseA);
            }

            _context.SaveChanges();
        }

        //ASIENTO F
        private void CrearAsientoF(Vuelo vuelo)
        {
            // Obtener el ID del vuelo recién creado
            var nuevoVueloId = vuelo.IdVuelo;

            for (int numeroAsiento = 1; numeroAsiento <= 29; numeroAsiento++)
            {

                if (numeroAsiento == 4)
                {
                    // Saltar el número 4
                    continue;
                };
                if (numeroAsiento >= 11 && numeroAsiento <= 17)
                {
                    // Saltar el rango del 11 al 17
                    continue;
                }


                var numeroAsientoFormateadoA = "F" + numeroAsiento.ToString("D2");

                var asientoPrimeraClaseA = new Asiento
                {
                    NumAsiento = numeroAsientoFormateadoA,
                    Clase = ObtenerClaseDelAsiento(numeroAsiento),
                    Disponibilidad = "DISPONIBLE",
                    PrecioV = ObtenerPrecioDeLaClase(ObtenerClaseDelAsiento(numeroAsiento)),
                    IdVuelo = nuevoVueloId
                };


                _context.Asientos.Add(asientoPrimeraClaseA);
            }

            _context.SaveChanges();
        }


        //ASIENTO B

        private void CrearAsientoB(Vuelo vuelo)
        {
            // Obtener el ID del vuelo recién creado
            var nuevoVueloId = vuelo.IdVuelo;

            for (int numeroAsiento = 1; numeroAsiento <= 29; numeroAsiento++)
            {

                if (numeroAsiento == 4)
                {
                    // Saltar el número 4
                    continue;
                };
                if (numeroAsiento >= 11 && numeroAsiento <= 16)
                {
                    // Saltar el rango del 11 al 17
                    continue;
                }


                var numeroAsientoFormateadoA = "B" + numeroAsiento.ToString("D2");

                var asientoPrimeraClaseA = new Asiento
                {
                    NumAsiento = numeroAsientoFormateadoA,
                    Clase = ObtenerClaseDelAsiento(numeroAsiento),
                    Disponibilidad = "DISPONIBLE",
                    PrecioV = ObtenerPrecioDeLaClase(ObtenerClaseDelAsiento(numeroAsiento)),
                    IdVuelo = nuevoVueloId
                };


                _context.Asientos.Add(asientoPrimeraClaseA);
            }

            _context.SaveChanges();
        }


        //ASIENTO E
        private void CrearAsientoE(Vuelo vuelo)
        {
            // Obtener el ID del vuelo recién creado
            var nuevoVueloId = vuelo.IdVuelo;

            for (int numeroAsiento = 1; numeroAsiento <= 29; numeroAsiento++)
            {

                if (numeroAsiento == 4)
                {
                    // Saltar el número 4
                    continue;
                };
                if (numeroAsiento >= 11 && numeroAsiento <= 16)
                {
                    // Saltar el rango del 11 al 17
                    continue;
                }


                var numeroAsientoFormateadoA = "E" + numeroAsiento.ToString("D2");

                var asientoPrimeraClaseA = new Asiento
                {
                    NumAsiento = numeroAsientoFormateadoA,
                    Clase = ObtenerClaseDelAsiento(numeroAsiento),
                    Disponibilidad = "DISPONIBLE",
                    PrecioV = ObtenerPrecioDeLaClase(ObtenerClaseDelAsiento(numeroAsiento)),
                    IdVuelo = nuevoVueloId
                };


                _context.Asientos.Add(asientoPrimeraClaseA);
            }

            _context.SaveChanges();
        }

        //ASIENTO C
        private void CrearAsientoC(Vuelo vuelo)
        {
            // Obtener el ID del vuelo recién creado
            var nuevoVueloId = vuelo.IdVuelo;

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agencia Viajes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgenciaViajes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Agencia de Viajes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendedors" asp-action="Index">Vendedor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aeropuerts" asp-action="Index">Aeropuerto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aerolineas" asp-action="Index">Aerolinea</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vueloes" asp-action="Index">Vuelo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tours" asp-action="Index">Tour</a>
                        </li>
                        <form class="form-inline">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Home" asp-action="Welcome">Salida</a>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AgenciaViajes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layoutvendedor.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgenciaViajes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgenciaViajes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Indexvendedor">AgenciaViajes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegistroVueloes" asp-action="Index">Reserva asiento vuelo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Detallecompras" asp-action="Index">Generar venta</a>
                        </li>
                        <form class="form-inline">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Home" asp-action="Welcome">Salida</a>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AgenciaViajes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>