Models/ReservaHotel.cs
using AgenciaViajes.Validations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AgenciaViajes.Models;

public partial class ReservaHotel : IValidatableObject
{
    public int IdPrh { get; set; }

    [Required(ErrorMessage = "El campo es obligatorio.")]
    public string? Dni { get; set; }

    [Required(ErrorMessage = "El campo es obligatorio.")]
    public int? IdHotel { get; set; }

    [Required(ErrorMessage = "El campo es obligatorio.")]
    public int? IdProductoTh { get; set; }

    [Required(ErrorMessage = "El campo Fecha Entrada es obligatorio.")]
    [FechaEntradaValidacion(ErrorMessage = "La fecha de entrada no es válida")]
    public DateTime FechaEntrada { get; set; }

    [Required(ErrorMessage = "El campo Fecha Salida es obligatorio.")]
    public DateTime FechaSalida { get; set; }

    public decimal Total { get; set; }

    public string? Estado { get; set; }

    public virtual ICollection<Detallecompra> Detallecompras { get; set; } = new List<Detallecompra>();


    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (FechaSalida <= FechaEntrada)
        {
            yield return new ValidationResult("La fecha de salida debe ser posterior a la fecha de entrada.", new[] { "FechaSalida" });
        }
    }

    public virtual Usuario? DniNavigation { get; set; }

    public virtual Estado? EstadoNavigation { get; set; }

    public virtual Hotel? IdHotelNavigation { get; set; }

    public virtual Thabitacion? IdProductoThNavigation { get; set; }
}

Controllers/ReservaHotelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgenciaViajes.Models;

namespace AgenciaViajes.Controllers
{
    public class ReservaHotelsController : Controller
    {
        private readonly AgenciaVContext _context;

        public ReservaHotelsController(AgenciaVContext context)
        {
            _context = context;
        }

        // GET: ReservaHotels
        public async Task<IActionResult> Index()
        {
            var agenciaVContext = _context.ReservaHotels.Include(r => r.DniNavigation).Include(r => r.EstadoNavigation).Include(r => r.IdHotelNavigation).Include(r => r.IdProductoThNavigation);
            return View(await agenciaVContext.ToListAsync());
        }

        // GET: ReservaHotels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ReservaHotels == null)
            {
                return NotFound();
            }

            var reservaHotel = await _context.ReservaHotels
                .Include(r => r.DniNavigation)
                .Include(r => r.EstadoNavigation)
                .Include(r => r.IdHotelNavigation)
                .Include(r => r.IdProductoThNavigation)
                .FirstOrDefaultAsync(m => m.IdPrh == id);
            if (reservaHotel == null)
            {
                return NotFound();
            }

            return View(reservaHotel);
        }

        // GET: ReservaHotels/Create
        public IActionResult Create()
        {

            var modeloUsuarios = _context.Usuarios.Where(m => m.Estado == "HABILITADO").ToList();
            var modeloHotels = _context.Hotels.Where(m => m.Estado == "HABILITADO").ToList();
            var thaabitacion = _context.Thabitacions.Where(m => m.Disponibilidad == "DISPONIBLE").ToList();

            ViewData["Dni"] = new SelectList(modeloUsuarios, "Dni", "Dni");
            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1");
            ViewData["IdHotel"] = new SelectList(modeloHotels, "IdHotel", "Nombre");
            ViewData["IdProductoTh"] = new SelectList(thaabitacion, "IdProductoTh", "IdProductoTh");
            return View();
        }

        // POST: ReservaHotels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPrh,Dni,IdHotel,IdProductoTh,FechaEntrada,FechaSalida,Total,Estado")] ReservaHotel reservaHotel)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrWhiteSpace(reservaHotel.Estado))
                {
                    reservaHotel.Estado = "HABILITADO"; // Establece el valor por defecto si no se especifica
                }
                // Cambiar el estado de la habitación a "OCUPADO"
                var habitacion = _context.Thabitacions.FirstOrDefault(th => th.IdProductoTh == reservaHotel.IdProductoTh);
                if (habitacion != null)
                {
                    habitacion.Disponibilidad = "OCUPADO";
                    _context.Update(habitacion);
                    await _context.SaveChangesAsync();
                }

                _context.Add(reservaHotel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Dni"] = new SelectList(_context.Usuarios, "Dni", "Dni", reservaHotel.Dni);
            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1", reservaHotel.Estado);
            ViewData["IdHotel"] = new SelectList(_context.Hotels, "IdHotel", "Nombre", reservaHotel.IdHotel);
            ViewData["IdProductoTh"] = new SelectList(_context.Thabitacions, "IdProductoTh", "IdProductoTh", reservaHotel.IdProductoTh);
            return View(reservaHotel);
        }

        // GET: ReservaHotels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ReservaHotels == null)
            {
                return NotFound();
            }

            var reservaHotel = await _context.ReservaHotels.FindAsync(id);
            if (reservaHotel == null)
            {
                return NotFound();
            }
            ViewData["Dni"] = new SelectList(_context.Usuarios, "Dni", "Dni", reservaHotel.Dni);
            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1", reservaHotel.Estado);
            ViewData["IdHotel"] = new SelectList(_context.Hotels, "IdHotel", "Nombre", reservaHotel.IdHotel);
            ViewData["IdProductoTh"] = new SelectList(_context.Thabitacions, "IdProductoTh", "IdProductoTh", reservaHotel.IdProductoTh);
            return View(reservaHotel);
        }

        // POST: ReservaHotels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPrh,Dni,IdHotel,IdProductoTh,FechaEntrada,FechaSalida,Total,Estado")] ReservaHotel reservaHotel)
        {
            if (id != reservaHotel.IdPrh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservaHotel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservaHotelExists(reservaHotel.IdPrh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Dni"] = new SelectList(_context.Usuarios, "Dni", "Dni", reservaHotel.Dni);
            ViewData["Estado"] = new SelectList(_context.Estados, "Estado1", "Estado1", reservaHotel.Estado);
            ViewData["IdHotel"] = new SelectList(_context.Hotels, "IdHotel", "IdHotel", reservaHotel.IdHotel);
            ViewData["IdProductoTh"] = new SelectList(_context.Thabitacions, "IdProductoTh", "IdProductoTh", reservaHotel.IdProductoTh);
            return View(reservaHotel);
        }

        // GET: ReservaHotels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ReservaHotels == null)
            {
                return NotFound();
            }

            var reservaHotel = await _context.ReservaHotels
                .Include(r => r.DniNavigation)
                .Include(r => r.EstadoNavigation)
                .Include(r => r.IdHotelNavigation)
                .Include(r => r.IdProductoThNavigation)
                .FirstOrDefaultAsync(m => m.IdPrh == id);
            if (reservaHotel == null)
            {
                return NotFound();
            }

            return View(reservaHotel);
        }

        // POST: ReservaHotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ReservaHotels == null)
            {
                return Problem("Entity set 'AgenciaVContext.ReservaHotels'  is null.");
            }
            var reservaHotel = await _context.ReservaHotels.FindAsync(id);
            if (reservaHotel != null)
            {
                reservaHotel.Estado = "DESHABILITADO"; // Cambiar el estado en lugar de eliminar
                _context.Update(reservaHotel); // Actualizar el estado en la base de datos
                await _context.SaveChangesAsync();
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult GetProductoThByHotel(int idHotel)
        {
            var productoThList = _context.Thabitacions
                .Where(th => th.IdHotel == idHotel && th.Disponibilidad=="DISPONIBLE")
                .Select(th => new { value = th.IdProductoTh, text = th.Habitacion })
                .ToList();

            return Json(productoThList);
        }

        [HttpGet]
        public IActionResult GetPrecioByIdProductoTh(int idProductoTh)
        {
            var precio = _context.Thabitacions
                .Where(th => th.IdProductoTh == idProductoTh)
                .Select(th => th.Precio)
                .FirstOrDefault();

            return Json(precio);
        }




        private bool ReservaHotelExists(int id)
        {
            return (_context.ReservaHotels?.Any(e => e.IdPrh == id)).GetValueOrDefault();
        }
    }



}

Views/ReservaHotels/Create.cshtml
@model AgenciaViajes.Models.ReservaHotel

@{
    ViewData["Title"] = "Crear";
}

<h1>Reservar hotel</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Dni" class="control-label"></label>
                <select asp-for="Dni" class="form-control" asp-items="ViewBag.Dni">
                    <option value="">Seleccionar...</option> <!-- Opción nula (null) -->

                </select>
            </div>
            <div class="form-group">
                <label asp-for="IdHotel" class="control-label">Hotel</label>
                <select asp-for="IdHotel" class="form-control" asp-items="ViewBag.IdHotel" id="IdHotelSelect">
                    <option value="">Seleccione una opción...</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="IdProductoTh" class="control-label">Habitación</label>
                <select asp-for="IdProductoTh" class="form-control" asp-items="ViewBag.IdProductoTh" id="IdProductoThSelect">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="FechaEntrada" class="control-label">Fecha entrada</label>
                <input asp-for="FechaEntrada" class="form-control" id="FechaEntrada" />
                <span asp-validation-for="FechaEntrada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaSalida" class="control-label">Fecha salida</label>
                <input asp-for="FechaSalida" class="form-control" id="FechaSalida" />
                <span asp-validation-for="FechaSalida" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" readonly id="Total" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Cuando cambie la selección de IdHotel
        $('#IdProductoThSelect').empty();
        $('#IdHotelSelect').change(function () {
            var selectedHotelId = $(this).val();
            if (selectedHotelId) {
                // Realiza una solicitud AJAX para cargar los elementos correspondientes de IdProductoTh
                $.ajax({
                    url: '@Url.Action("GetProductoThByHotel", "ReservaHotels")',
                    type: 'GET',
                    data: { idHotel: selectedHotelId },
                    success: function (data) {
                        // Actualiza la lista desplegable de IdProductoTh
                        $('#IdProductoThSelect').empty();
                        $.each(data, function (i, item) {
                            $('#IdProductoThSelect').append($('<option>').val(item.value).text(item.text));
                        });
                    }
                });
            }
            else {
                // Si no se ha seleccionado un valor en IdHotel, deja la lista desplegable de IdProductoTh vacía
                $('#IdProductoThSelect').empty();
                $('#IdProductoThSelect').append($('<option value="">Seleccione una opción...</option>'));
            }
        });
    </script>
    <script>
        // Cuando cambien las fechas FechaEntrada o FechaSalida
        $('#FechaEntrada, #FechaSalida').change(function () {
            var fechaEntrada = $('#FechaEntrada').val();
            var fechaSalida = $('#FechaSalida').val();

            if (fechaEntrada && fechaSalida) {
                // Convierte las fechas a objetos Date
                var fechaEntradaObj = new Date(fechaEntrada);
                var fechaSalidaObj = new Date(fechaSalida);

                // Calcula la diferencia en días
                var diferenciaDias = (fechaSalidaObj - fechaEntradaObj) / (1000 * 60 * 60 * 24);

                // Obtiene el valor de Precio usando una solicitud AJAX basada en IdProductoTh
                var idProductoTh = $('#IdProductoThSelect').val();

                if (idProductoTh) {
                    $.ajax({
                        url: '@Url.Action("GetPrecioByIdProductoTh", "ReservaHotels")',
                        type: 'GET',
                        data: { idProductoTh: idProductoTh },
                        success: function (precio) {
                            // Calcula el Total y muestra el resultado
                            var total = precio * diferenciaDias;
                            $('#Total').val(total);
                        }
                    });
                }
            }
        });
    </script>


}

Views/ReservaHotels/Delete.cshtml
@model AgenciaViajes.Models.ReservaHotel

@{
    ViewData["Title"] = "Deshabilitar";
}

<h1>Deshabilitar</h1>

<h3>¿Seguro deseas deshabilitar?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Fecha de entrada
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaEntrada)
        </dd>
        <dt class = "col-sm-2">
            Fecha de salida
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            DNI
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DniNavigation.Dni)
        </dd>
        <dt class = "col-sm-2">
            Estado
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoNavigation.Estado1)
        </dd>
        <dt class = "col-sm-2">
            Hotel
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHotelNavigation.Nombre)
        </dd>
        <dt class = "col-sm-2">
            Habitación
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProductoThNavigation.Habitacion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPrh" />
        <input type="submit" value="Deshabilitar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/ReservaHotels/Details.cshtml
@model AgenciaViajes.Models.ReservaHotel

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Fecha de entrada
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaEntrada)
        </dd>
        <dt class = "col-sm-2">
            Fecha de salida
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            DNI
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DniNavigation.Dni)
        </dd>
        <dt class = "col-sm-2">
            Estado
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoNavigation.Estado1)
        </dd>
        <dt class = "col-sm-2">
            Hotel
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHotelNavigation.Nombre)
        </dd>
        <dt class = "col-sm-2">
            Habitación
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProductoThNavigation.Habitacion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdPrh">Editar</a> |
    <a asp-action="Index">Volver</a>
</div>

Views/ReservaHotels/Edit.cshtml
@model AgenciaViajes.Models.ReservaHotel

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>ReservaHotel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPrh" />
            <div class="form-group">
                <label asp-for="Dni" class="control-label">DNI</label>
                <select asp-for="Dni" class="form-control" asp-items="ViewBag.Dni"></select>
                <span asp-validation-for="Dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdHotel" class="control-label">Hotel</label>
                <select asp-for="IdHotel" class="form-control" asp-items="ViewBag.IdHotel" id="IdHotelSelect">
                    <option value="">Seleccione una opción...</option>
                </select>
                <span asp-validation-for="IdHotel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdProductoTh" class="control-label">Habitación</label>
                <select asp-for="IdProductoTh" class="form-control" asp-items="ViewBag.IdProductoTh" id="IdProductoThSelect"></select>
                <span asp-validation-for="IdProductoTh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaEntrada" class="control-label">Fecha entrada</label>
                <input asp-for="FechaEntrada" class="form-control" id="FechaEntrada" />
                <span asp-validation-for="FechaEntrada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaSalida" class="control-label">Fecha salida</label>
                <input asp-for="FechaSalida" class="form-control" id="FechaSalida" />
                <span asp-validation-for="FechaSalida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" readonly id="Total" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control" asp-items="ViewBag.Estado"></select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        // Cuando cambie la selección de IdHotel
        $('#IdProductoThSelect').empty();
        $('#IdHotelSelect').change(function () {
            var selectedHotelId = $(this).val();
            if (selectedHotelId) {
                // Realiza una solicitud AJAX para cargar los elementos correspondientes de IdProductoTh
                $.ajax({
                    url: '@Url.Action("GetProductoThByHotel", "ReservaHotels")',
                    type: 'GET',
                    data: { idHotel: selectedHotelId },
                    success: function (data) {
                        // Actualiza la lista desplegable de IdProductoTh
                        $('#IdProductoThSelect').empty();
                        $.each(data, function (i, item) {
                            $('#IdProductoThSelect').append($('<option>').val(item.value).text(item.text));
                        });
                    }
                });
            }
            else {
                // Si no se ha seleccionado un valor en IdHotel, deja la lista desplegable de IdProductoTh vacía
                $('#IdProductoThSelect').empty();
                $('#IdProductoThSelect').append($('<option value="">Seleccione una opción...</option>'));
            }
        });
    </script>
    <script>
        // Cuando cambien las fechas FechaEntrada o FechaSalida
        $('#FechaEntrada, #FechaSalida').change(function () {
            var fechaEntrada = $('#FechaEntrada').val();
            var fechaSalida = $('#FechaSalida').val();

            if (fechaEntrada && fechaSalida) {
                // Convierte las fechas a objetos Date
                var fechaEntradaObj = new Date(fechaEntrada);
                var fechaSalidaObj = new Date(fechaSalida);

                // Calcula la diferencia en días
                var diferenciaDias = (fechaSalidaObj - fechaEntradaObj) / (1000 * 60 * 60 * 24);

                // Obtiene el valor de Precio usando una solicitud AJAX basada en IdProductoTh
                var idProductoTh = $('#IdProductoThSelect').val();

                if (idProductoTh) {
                    $.ajax({
                        url: '@Url.Action("GetPrecioByIdProductoTh", "ReservaHotels")',
                        type: 'GET',
                        data: { idProductoTh: idProductoTh },
                        success: function (precio) {
                            // Calcula el Total y muestra el resultado
                            var total = precio * diferenciaDias;
                            $('#Total').val(total);
                        }
                    });
                }
            }
        });
    </script>
}

Views/ReservaHotels/Index.cshtml
@model IEnumerable<AgenciaViajes.Models.ReservaHotel>

@{
    ViewData["Title"] = "Reservar hotel";
}

<h1>Reservar hotel</h1>

<p>
    <a asp-action="Create">Agregar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               Fecha entrada
            </th>
            <th>
                Fecha salida
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                DNI
            </th>
            <th>
                Estado
            </th>
            <th>
                Hotel
            </th>
            <th>
                Habitación
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FechaEntrada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaSalida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DniNavigation.Dni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstadoNavigation.Estado1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdHotelNavigation.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdProductoThNavigation.Habitacion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdPrh">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.IdPrh">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.IdPrh">Deshabilitar</a>
            </td>
        </tr>
}
    </tbody>
</table>